apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ecommerce
            - name: POSTGRES_PASSWORD
              value: pg123
            - name: POSTGRES_DB
              value: ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels: 
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: pedroar9/fake-shop-desafio:v2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: ecommerce
            - name: DB_PASSWORD
              value: pg123
            - name: DB_NAME
              value: ecommerce
            - name: FLASK_APP
              value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer